import { Router } from "express";
import { isAuthenticated, login, logout, register, sendVerifyOtp, verifyEmail } from "../controllers/auth.controller.js";
import userAuth from "../middlewares/userAuth.middleware.js";
const authRouter = Router();
authRouter.post('/register', register);
authRouter.post('/login', login);
authRouter.post('/logout', logout);
authRouter.post('/send-verify-otp', userAuth, sendVerifyOtp);
authRouter.post('/verify-account', userAuth, verifyEmail);
authRouter.post('/is-auth', userAuth, isAuthenticated);
export default authRouter;